import axios from 'axios';
import { getQMetrySettings } from './settingsService';

const getProxyUrl = () => window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' 
  ? 'http://127.0.0.1:3001' 
  : window.location.origin;

/**
 * Transforms test cases into QMetry-compatible payload format
 * Format:
 * {
 *   "name": "<Test Case Name>",
 *   "description": "<Optional>",
 *   "testSteps": [
 *     {
 *       "description": "<Step>",
 *       "expectedResult": "<Expected>"
 *     }
 *   ],
 *   "issueLinks": ["<JIRA-KEY>"]
 * }
 */
export const transformToQMetryPayload = (testCase, jiraKey) => {
  // Attempt to parse Gherkin into steps, or just use the whole text if not formatted properly
  const stepsText = testCase.Gherkin || testCase['Test Steps'] || testCase['Steps'] || '';
  const lines = stepsText.split('\n').filter(l => l.trim().length > 0);
  
  const testSteps = lines.map(line => ({
    description: line.trim(),
    expectedResult: testCase.Expected_Result || ''
  }));

  // Ensure at least one step if none could be parsed
  if (testSteps.length === 0) {
    testSteps.push({
      description: testCase.Scenario_Name || testCase['Test Case Name'] || 'Execute Test Scenario',
      expectedResult: testCase.Expected_Result || ''
    });
  }

  return {
    name: testCase.Scenario_Name || testCase['Test Case Name'] || testCase['TC_ID'] || 'Generated Test Case',
    description: `Generated by TestPilot AI.\nType: ${testCase.Type || 'Unknown'}`,
    testSteps: testSteps,
    issueLinks: jiraKey ? [jiraKey] : []
  };
};

export const testQMetryConnection = async (settings) => {
  const PROXY_URL = getProxyUrl();
  try {
    const response = await axios.post(`${PROXY_URL}/api/qmetry/test`, settings);
    return response.data;
  } catch (error) {
    const backendError = error.response?.data?.error || error.message;
    throw new Error(backendError);
  }
};

export const syncTestCasesToQMetry = async (testCases, jiraKey) => {
  const PROXY_URL = getProxyUrl();
  const settings = getQMetrySettings();
  
  if (!settings || !settings.qmetryBaseUrl || !settings.apiToken) {
    throw new Error("QMetry settings are incomplete. Please configure them in Settings.");
  }

  const results = [];
  
  for (const tc of testCases) {
    const payload = transformToQMetryPayload(tc, jiraKey);
    try {
      const response = await axios.post(`${PROXY_URL}/api/qmetry/sync`, {
        settings,
        payload
      });
      results.push({
        tcId: tc.TC_ID,
        name: payload.name,
        status: 'Success',
        qmetryId: response.data?.id || response.data?.key,
        message: 'Successfully synced'
      });
    } catch (error) {
      results.push({
        tcId: tc.TC_ID,
        name: payload.name,
        status: 'Failed',
        qmetryId: null,
        message: error.response?.data?.error || error.message
      });
    }
  }
  
  return results;
};
